// Code generated by protoc-gen-go. DO NOT EDIT.
// source: authpb/authpb.proto

package authpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CheckServerStatusRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckServerStatusRequest) Reset()         { *m = CheckServerStatusRequest{} }
func (m *CheckServerStatusRequest) String() string { return proto.CompactTextString(m) }
func (*CheckServerStatusRequest) ProtoMessage()    {}
func (*CheckServerStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3057ffcbf9655ca4, []int{0}
}

func (m *CheckServerStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckServerStatusRequest.Unmarshal(m, b)
}
func (m *CheckServerStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckServerStatusRequest.Marshal(b, m, deterministic)
}
func (m *CheckServerStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckServerStatusRequest.Merge(m, src)
}
func (m *CheckServerStatusRequest) XXX_Size() int {
	return xxx_messageInfo_CheckServerStatusRequest.Size(m)
}
func (m *CheckServerStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckServerStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckServerStatusRequest proto.InternalMessageInfo

type CheckServerStatusResponse struct {
	ServerName           string   `protobuf:"bytes,1,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	Host                 string   `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port                 string   `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
	Time                 string   `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	Status               string   `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckServerStatusResponse) Reset()         { *m = CheckServerStatusResponse{} }
func (m *CheckServerStatusResponse) String() string { return proto.CompactTextString(m) }
func (*CheckServerStatusResponse) ProtoMessage()    {}
func (*CheckServerStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3057ffcbf9655ca4, []int{1}
}

func (m *CheckServerStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckServerStatusResponse.Unmarshal(m, b)
}
func (m *CheckServerStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckServerStatusResponse.Marshal(b, m, deterministic)
}
func (m *CheckServerStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckServerStatusResponse.Merge(m, src)
}
func (m *CheckServerStatusResponse) XXX_Size() int {
	return xxx_messageInfo_CheckServerStatusResponse.Size(m)
}
func (m *CheckServerStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckServerStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckServerStatusResponse proto.InternalMessageInfo

func (m *CheckServerStatusResponse) GetServerName() string {
	if m != nil {
		return m.ServerName
	}
	return ""
}

func (m *CheckServerStatusResponse) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *CheckServerStatusResponse) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *CheckServerStatusResponse) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *CheckServerStatusResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type RegisterAccountRequest struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	ConfirmPassword      string   `protobuf:"bytes,6,opt,name=confirm_password,json=confirmPassword,proto3" json:"confirm_password,omitempty"`
	CompanyTerms         bool     `protobuf:"varint,7,opt,name=company_terms,json=companyTerms,proto3" json:"company_terms,omitempty"`
	GovtTerms            bool     `protobuf:"varint,8,opt,name=govt_terms,json=govtTerms,proto3" json:"govt_terms,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterAccountRequest) Reset()         { *m = RegisterAccountRequest{} }
func (m *RegisterAccountRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterAccountRequest) ProtoMessage()    {}
func (*RegisterAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3057ffcbf9655ca4, []int{2}
}

func (m *RegisterAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterAccountRequest.Unmarshal(m, b)
}
func (m *RegisterAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterAccountRequest.Marshal(b, m, deterministic)
}
func (m *RegisterAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterAccountRequest.Merge(m, src)
}
func (m *RegisterAccountRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterAccountRequest.Size(m)
}
func (m *RegisterAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterAccountRequest proto.InternalMessageInfo

func (m *RegisterAccountRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *RegisterAccountRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *RegisterAccountRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterAccountRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterAccountRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterAccountRequest) GetConfirmPassword() string {
	if m != nil {
		return m.ConfirmPassword
	}
	return ""
}

func (m *RegisterAccountRequest) GetCompanyTerms() bool {
	if m != nil {
		return m.CompanyTerms
	}
	return false
}

func (m *RegisterAccountRequest) GetGovtTerms() bool {
	if m != nil {
		return m.GovtTerms
	}
	return false
}

type RegisterAccountResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterAccountResponse) Reset()         { *m = RegisterAccountResponse{} }
func (m *RegisterAccountResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterAccountResponse) ProtoMessage()    {}
func (*RegisterAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3057ffcbf9655ca4, []int{3}
}

func (m *RegisterAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterAccountResponse.Unmarshal(m, b)
}
func (m *RegisterAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterAccountResponse.Marshal(b, m, deterministic)
}
func (m *RegisterAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterAccountResponse.Merge(m, src)
}
func (m *RegisterAccountResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterAccountResponse.Size(m)
}
func (m *RegisterAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterAccountResponse proto.InternalMessageInfo

func (m *RegisterAccountResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func (m *RegisterAccountResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type LoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3057ffcbf9655ca4, []int{4}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3057ffcbf9655ca4, []int{5}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type UpdateAccountRequest struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAccountRequest) Reset()         { *m = UpdateAccountRequest{} }
func (m *UpdateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateAccountRequest) ProtoMessage()    {}
func (*UpdateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3057ffcbf9655ca4, []int{6}
}

func (m *UpdateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAccountRequest.Unmarshal(m, b)
}
func (m *UpdateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAccountRequest.Marshal(b, m, deterministic)
}
func (m *UpdateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAccountRequest.Merge(m, src)
}
func (m *UpdateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateAccountRequest.Size(m)
}
func (m *UpdateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAccountRequest proto.InternalMessageInfo

func (m *UpdateAccountRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UpdateAccountRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *UpdateAccountRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UpdateAccountRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type UpdateAccountResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAccountResponse) Reset()         { *m = UpdateAccountResponse{} }
func (m *UpdateAccountResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateAccountResponse) ProtoMessage()    {}
func (*UpdateAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3057ffcbf9655ca4, []int{7}
}

func (m *UpdateAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAccountResponse.Unmarshal(m, b)
}
func (m *UpdateAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAccountResponse.Marshal(b, m, deterministic)
}
func (m *UpdateAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAccountResponse.Merge(m, src)
}
func (m *UpdateAccountResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateAccountResponse.Size(m)
}
func (m *UpdateAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAccountResponse proto.InternalMessageInfo

func (m *UpdateAccountResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func (m *UpdateAccountResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type GetAccountDetailsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountDetailsRequest) Reset()         { *m = GetAccountDetailsRequest{} }
func (m *GetAccountDetailsRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccountDetailsRequest) ProtoMessage()    {}
func (*GetAccountDetailsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3057ffcbf9655ca4, []int{8}
}

func (m *GetAccountDetailsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountDetailsRequest.Unmarshal(m, b)
}
func (m *GetAccountDetailsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountDetailsRequest.Marshal(b, m, deterministic)
}
func (m *GetAccountDetailsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountDetailsRequest.Merge(m, src)
}
func (m *GetAccountDetailsRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccountDetailsRequest.Size(m)
}
func (m *GetAccountDetailsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountDetailsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountDetailsRequest proto.InternalMessageInfo

type GetAccountDetailsResponse struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountDetailsResponse) Reset()         { *m = GetAccountDetailsResponse{} }
func (m *GetAccountDetailsResponse) String() string { return proto.CompactTextString(m) }
func (*GetAccountDetailsResponse) ProtoMessage()    {}
func (*GetAccountDetailsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3057ffcbf9655ca4, []int{9}
}

func (m *GetAccountDetailsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountDetailsResponse.Unmarshal(m, b)
}
func (m *GetAccountDetailsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountDetailsResponse.Marshal(b, m, deterministic)
}
func (m *GetAccountDetailsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountDetailsResponse.Merge(m, src)
}
func (m *GetAccountDetailsResponse) XXX_Size() int {
	return xxx_messageInfo_GetAccountDetailsResponse.Size(m)
}
func (m *GetAccountDetailsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountDetailsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountDetailsResponse proto.InternalMessageInfo

func (m *GetAccountDetailsResponse) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *GetAccountDetailsResponse) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *GetAccountDetailsResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetAccountDetailsResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type ChangePasswordRequest struct {
	OldPassword          string   `protobuf:"bytes,1,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	NewPassword          string   `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	ConfirmPassword      string   `protobuf:"bytes,3,opt,name=confirm_password,json=confirmPassword,proto3" json:"confirm_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordRequest) Reset()         { *m = ChangePasswordRequest{} }
func (m *ChangePasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordRequest) ProtoMessage()    {}
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3057ffcbf9655ca4, []int{10}
}

func (m *ChangePasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordRequest.Unmarshal(m, b)
}
func (m *ChangePasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordRequest.Marshal(b, m, deterministic)
}
func (m *ChangePasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordRequest.Merge(m, src)
}
func (m *ChangePasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordRequest.Size(m)
}
func (m *ChangePasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordRequest proto.InternalMessageInfo

func (m *ChangePasswordRequest) GetOldPassword() string {
	if m != nil {
		return m.OldPassword
	}
	return ""
}

func (m *ChangePasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

func (m *ChangePasswordRequest) GetConfirmPassword() string {
	if m != nil {
		return m.ConfirmPassword
	}
	return ""
}

type ChangePasswordResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordResponse) Reset()         { *m = ChangePasswordResponse{} }
func (m *ChangePasswordResponse) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordResponse) ProtoMessage()    {}
func (*ChangePasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3057ffcbf9655ca4, []int{11}
}

func (m *ChangePasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordResponse.Unmarshal(m, b)
}
func (m *ChangePasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordResponse.Marshal(b, m, deterministic)
}
func (m *ChangePasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordResponse.Merge(m, src)
}
func (m *ChangePasswordResponse) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordResponse.Size(m)
}
func (m *ChangePasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordResponse proto.InternalMessageInfo

func (m *ChangePasswordResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func (m *ChangePasswordResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type GetAllAccountsRequest struct {
	Skip                 int64    `protobuf:"varint,2,opt,name=skip,proto3" json:"skip,omitempty"`
	Limit                int64    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllAccountsRequest) Reset()         { *m = GetAllAccountsRequest{} }
func (m *GetAllAccountsRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllAccountsRequest) ProtoMessage()    {}
func (*GetAllAccountsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3057ffcbf9655ca4, []int{12}
}

func (m *GetAllAccountsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllAccountsRequest.Unmarshal(m, b)
}
func (m *GetAllAccountsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllAccountsRequest.Marshal(b, m, deterministic)
}
func (m *GetAllAccountsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllAccountsRequest.Merge(m, src)
}
func (m *GetAllAccountsRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllAccountsRequest.Size(m)
}
func (m *GetAllAccountsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllAccountsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllAccountsRequest proto.InternalMessageInfo

func (m *GetAllAccountsRequest) GetSkip() int64 {
	if m != nil {
		return m.Skip
	}
	return 0
}

func (m *GetAllAccountsRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type GetAllAccountsResponse struct {
	FfId                 string   `protobuf:"bytes,1,opt,name=ff_id,json=ffId,proto3" json:"ff_id,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Username             string   `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	CreatedTime          int64    `protobuf:"varint,6,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	Status               string   `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllAccountsResponse) Reset()         { *m = GetAllAccountsResponse{} }
func (m *GetAllAccountsResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllAccountsResponse) ProtoMessage()    {}
func (*GetAllAccountsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3057ffcbf9655ca4, []int{13}
}

func (m *GetAllAccountsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllAccountsResponse.Unmarshal(m, b)
}
func (m *GetAllAccountsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllAccountsResponse.Marshal(b, m, deterministic)
}
func (m *GetAllAccountsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllAccountsResponse.Merge(m, src)
}
func (m *GetAllAccountsResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllAccountsResponse.Size(m)
}
func (m *GetAllAccountsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllAccountsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllAccountsResponse proto.InternalMessageInfo

func (m *GetAllAccountsResponse) GetFfId() string {
	if m != nil {
		return m.FfId
	}
	return ""
}

func (m *GetAllAccountsResponse) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *GetAllAccountsResponse) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *GetAllAccountsResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GetAllAccountsResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetAllAccountsResponse) GetCreatedTime() int64 {
	if m != nil {
		return m.CreatedTime
	}
	return 0
}

func (m *GetAllAccountsResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type GetAllSessionDetailsRequest struct {
	FfId                 string   `protobuf:"bytes,1,opt,name=ff_id,json=ffId,proto3" json:"ff_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllSessionDetailsRequest) Reset()         { *m = GetAllSessionDetailsRequest{} }
func (m *GetAllSessionDetailsRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllSessionDetailsRequest) ProtoMessage()    {}
func (*GetAllSessionDetailsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3057ffcbf9655ca4, []int{14}
}

func (m *GetAllSessionDetailsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllSessionDetailsRequest.Unmarshal(m, b)
}
func (m *GetAllSessionDetailsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllSessionDetailsRequest.Marshal(b, m, deterministic)
}
func (m *GetAllSessionDetailsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllSessionDetailsRequest.Merge(m, src)
}
func (m *GetAllSessionDetailsRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllSessionDetailsRequest.Size(m)
}
func (m *GetAllSessionDetailsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllSessionDetailsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllSessionDetailsRequest proto.InternalMessageInfo

func (m *GetAllSessionDetailsRequest) GetFfId() string {
	if m != nil {
		return m.FfId
	}
	return ""
}

type GetAllSessionDetailsResponse struct {
	FsId                 string   `protobuf:"bytes,1,opt,name=fs_id,json=fsId,proto3" json:"fs_id,omitempty"`
	LoggedIn             string   `protobuf:"bytes,2,opt,name=logged_in,json=loggedIn,proto3" json:"logged_in,omitempty"`
	CurrentStatus        string   `protobuf:"bytes,3,opt,name=current_status,json=currentStatus,proto3" json:"current_status,omitempty"`
	LastPing             string   `protobuf:"bytes,4,opt,name=last_ping,json=lastPing,proto3" json:"last_ping,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllSessionDetailsResponse) Reset()         { *m = GetAllSessionDetailsResponse{} }
func (m *GetAllSessionDetailsResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllSessionDetailsResponse) ProtoMessage()    {}
func (*GetAllSessionDetailsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3057ffcbf9655ca4, []int{15}
}

func (m *GetAllSessionDetailsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllSessionDetailsResponse.Unmarshal(m, b)
}
func (m *GetAllSessionDetailsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllSessionDetailsResponse.Marshal(b, m, deterministic)
}
func (m *GetAllSessionDetailsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllSessionDetailsResponse.Merge(m, src)
}
func (m *GetAllSessionDetailsResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllSessionDetailsResponse.Size(m)
}
func (m *GetAllSessionDetailsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllSessionDetailsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllSessionDetailsResponse proto.InternalMessageInfo

func (m *GetAllSessionDetailsResponse) GetFsId() string {
	if m != nil {
		return m.FsId
	}
	return ""
}

func (m *GetAllSessionDetailsResponse) GetLoggedIn() string {
	if m != nil {
		return m.LoggedIn
	}
	return ""
}

func (m *GetAllSessionDetailsResponse) GetCurrentStatus() string {
	if m != nil {
		return m.CurrentStatus
	}
	return ""
}

func (m *GetAllSessionDetailsResponse) GetLastPing() string {
	if m != nil {
		return m.LastPing
	}
	return ""
}

type CheckUsernameRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckUsernameRequest) Reset()         { *m = CheckUsernameRequest{} }
func (m *CheckUsernameRequest) String() string { return proto.CompactTextString(m) }
func (*CheckUsernameRequest) ProtoMessage()    {}
func (*CheckUsernameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3057ffcbf9655ca4, []int{16}
}

func (m *CheckUsernameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckUsernameRequest.Unmarshal(m, b)
}
func (m *CheckUsernameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckUsernameRequest.Marshal(b, m, deterministic)
}
func (m *CheckUsernameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckUsernameRequest.Merge(m, src)
}
func (m *CheckUsernameRequest) XXX_Size() int {
	return xxx_messageInfo_CheckUsernameRequest.Size(m)
}
func (m *CheckUsernameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckUsernameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckUsernameRequest proto.InternalMessageInfo

func (m *CheckUsernameRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type CheckUsernameResponse struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Avatar               string   `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckUsernameResponse) Reset()         { *m = CheckUsernameResponse{} }
func (m *CheckUsernameResponse) String() string { return proto.CompactTextString(m) }
func (*CheckUsernameResponse) ProtoMessage()    {}
func (*CheckUsernameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3057ffcbf9655ca4, []int{17}
}

func (m *CheckUsernameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckUsernameResponse.Unmarshal(m, b)
}
func (m *CheckUsernameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckUsernameResponse.Marshal(b, m, deterministic)
}
func (m *CheckUsernameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckUsernameResponse.Merge(m, src)
}
func (m *CheckUsernameResponse) XXX_Size() int {
	return xxx_messageInfo_CheckUsernameResponse.Size(m)
}
func (m *CheckUsernameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckUsernameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckUsernameResponse proto.InternalMessageInfo

func (m *CheckUsernameResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CheckUsernameResponse) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func init() {
	proto.RegisterType((*CheckServerStatusRequest)(nil), "authpb.CheckServerStatusRequest")
	proto.RegisterType((*CheckServerStatusResponse)(nil), "authpb.CheckServerStatusResponse")
	proto.RegisterType((*RegisterAccountRequest)(nil), "authpb.RegisterAccountRequest")
	proto.RegisterType((*RegisterAccountResponse)(nil), "authpb.RegisterAccountResponse")
	proto.RegisterType((*LoginRequest)(nil), "authpb.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "authpb.LoginResponse")
	proto.RegisterType((*UpdateAccountRequest)(nil), "authpb.UpdateAccountRequest")
	proto.RegisterType((*UpdateAccountResponse)(nil), "authpb.UpdateAccountResponse")
	proto.RegisterType((*GetAccountDetailsRequest)(nil), "authpb.GetAccountDetailsRequest")
	proto.RegisterType((*GetAccountDetailsResponse)(nil), "authpb.GetAccountDetailsResponse")
	proto.RegisterType((*ChangePasswordRequest)(nil), "authpb.ChangePasswordRequest")
	proto.RegisterType((*ChangePasswordResponse)(nil), "authpb.ChangePasswordResponse")
	proto.RegisterType((*GetAllAccountsRequest)(nil), "authpb.GetAllAccountsRequest")
	proto.RegisterType((*GetAllAccountsResponse)(nil), "authpb.GetAllAccountsResponse")
	proto.RegisterType((*GetAllSessionDetailsRequest)(nil), "authpb.GetAllSessionDetailsRequest")
	proto.RegisterType((*GetAllSessionDetailsResponse)(nil), "authpb.GetAllSessionDetailsResponse")
	proto.RegisterType((*CheckUsernameRequest)(nil), "authpb.CheckUsernameRequest")
	proto.RegisterType((*CheckUsernameResponse)(nil), "authpb.CheckUsernameResponse")
}

func init() { proto.RegisterFile("authpb/authpb.proto", fileDescriptor_3057ffcbf9655ca4) }

var fileDescriptor_3057ffcbf9655ca4 = []byte{
	// 839 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0xcd, 0x6e, 0xe3, 0x36,
	0x10, 0x86, 0xec, 0xd8, 0x6b, 0x8f, 0xed, 0x6c, 0x97, 0x6b, 0xbb, 0x5a, 0xed, 0x5f, 0xac, 0xed,
	0x02, 0xdb, 0x4b, 0x5a, 0xa4, 0x7d, 0x81, 0x20, 0x45, 0x53, 0xa3, 0x41, 0x9b, 0x3a, 0x09, 0x90,
	0x9b, 0xa0, 0x48, 0xb4, 0x4c, 0x44, 0x22, 0x55, 0x91, 0x4a, 0xd0, 0x7b, 0x0f, 0xed, 0xad, 0x05,
	0xfa, 0x6c, 0x7d, 0x8e, 0x3e, 0x42, 0x21, 0x92, 0xfa, 0x8d, 0x6c, 0x14, 0x39, 0x74, 0x4f, 0xe6,
	0x7c, 0x33, 0x1c, 0xcd, 0x7c, 0x24, 0xbf, 0x31, 0x3c, 0x77, 0x53, 0xb1, 0x89, 0x6f, 0xbe, 0x50,
	0x3f, 0x87, 0x71, 0xc2, 0x04, 0x43, 0x7d, 0x65, 0xd9, 0x16, 0x98, 0x27, 0x1b, 0xec, 0xdd, 0x5e,
	0xe0, 0xe4, 0x0e, 0x27, 0x17, 0xc2, 0x15, 0x29, 0x5f, 0xe1, 0x9f, 0x53, 0xcc, 0x85, 0xfd, 0x87,
	0x01, 0x2f, 0x5a, 0x9c, 0x3c, 0x66, 0x94, 0x63, 0xf4, 0x16, 0x46, 0x5c, 0xe2, 0x0e, 0x75, 0x23,
	0x6c, 0x1a, 0x07, 0xc6, 0x87, 0xe1, 0x0a, 0x14, 0xf4, 0x83, 0x1b, 0x61, 0x84, 0x60, 0x6f, 0xc3,
	0xb8, 0x30, 0x3b, 0xd2, 0x23, 0xd7, 0x19, 0x16, 0xb3, 0x44, 0x98, 0x5d, 0x85, 0x65, 0xeb, 0x0c,
	0x13, 0x24, 0xc2, 0xe6, 0x9e, 0xc2, 0xb2, 0x35, 0x9a, 0x43, 0x9f, 0xcb, 0xcf, 0x99, 0x3d, 0x89,
	0x6a, 0xcb, 0xfe, 0xb3, 0x03, 0xf3, 0x15, 0x0e, 0x08, 0x17, 0x38, 0x39, 0xf6, 0x3c, 0x96, 0x52,
	0xa1, 0xab, 0x45, 0xaf, 0x01, 0xd6, 0x24, 0xe1, 0xa2, 0x5a, 0xce, 0x50, 0x22, 0xb2, 0x9a, 0x97,
	0x30, 0x0c, 0xdd, 0xdc, 0xab, 0x4a, 0x1a, 0x64, 0x80, 0x74, 0x5a, 0x30, 0x48, 0x39, 0x4e, 0xa4,
	0x4f, 0x95, 0x56, 0xd8, 0x68, 0x0a, 0x3d, 0x1c, 0xb9, 0x24, 0xd4, 0xf5, 0x29, 0x23, 0xdb, 0x11,
	0xbb, 0x9c, 0xdf, 0xb3, 0xc4, 0xd7, 0x25, 0x16, 0x36, 0xfa, 0x1c, 0x3e, 0xf1, 0x18, 0x5d, 0x93,
	0x24, 0x72, 0x8a, 0x98, 0xbe, 0x8c, 0x79, 0xaa, 0xf1, 0xf3, 0x3c, 0xf4, 0x1d, 0x4c, 0x3c, 0x16,
	0xc5, 0x2e, 0xfd, 0xc5, 0x11, 0x38, 0x89, 0xb8, 0xf9, 0xe4, 0xc0, 0xf8, 0x30, 0x58, 0x8d, 0x35,
	0x78, 0x99, 0x61, 0x59, 0x67, 0x01, 0xbb, 0x13, 0x3a, 0x62, 0x20, 0x23, 0x86, 0x19, 0x22, 0xdd,
	0xf6, 0x12, 0x3e, 0x7d, 0x40, 0x89, 0x3e, 0xa3, 0x39, 0xf4, 0x13, 0xcc, 0xd3, 0x50, 0x68, 0x3e,
	0xb4, 0x55, 0xa1, 0xb7, 0x53, 0xa3, 0xf7, 0x5b, 0x18, 0x9f, 0xb1, 0x80, 0xd0, 0x9c, 0xd3, 0x2a,
	0x2f, 0x46, 0x83, 0x97, 0x2a, 0x03, 0x9d, 0x3a, 0x03, 0xf6, 0x7b, 0x98, 0xe8, 0x3c, 0xba, 0x90,
	0x29, 0xf4, 0x04, 0xbb, 0xc5, 0x54, 0x67, 0x51, 0x86, 0xfd, 0xab, 0x01, 0xd3, 0xab, 0xd8, 0x77,
	0x05, 0xfe, 0x98, 0x67, 0x69, 0x9f, 0xc2, 0xac, 0x51, 0xc5, 0x23, 0xe9, 0xb3, 0xc0, 0x3c, 0xc5,
	0x42, 0x67, 0xf9, 0x06, 0x0b, 0x97, 0x84, 0xc5, 0x63, 0xfa, 0xdd, 0x80, 0x17, 0x2d, 0x4e, 0xfd,
	0xa5, 0xff, 0xb7, 0xe1, 0xdf, 0x0c, 0x98, 0x9d, 0x6c, 0x5c, 0x1a, 0xe0, 0xfc, 0x22, 0xe6, 0xc4,
	0x2f, 0x60, 0xcc, 0x42, 0xbf, 0xbc, 0xb6, 0xaa, 0x92, 0x11, 0x0b, 0xfd, 0xe2, 0xca, 0x2e, 0x60,
	0x4c, 0xf1, 0xbd, 0xd3, 0x38, 0xfb, 0x11, 0xc5, 0xf7, 0xe7, 0xbb, 0x1e, 0x40, 0xb7, 0xf5, 0x01,
	0xd8, 0xdf, 0xc1, 0xbc, 0x59, 0xc9, 0x23, 0xc9, 0x3f, 0x86, 0x59, 0xc6, 0x6f, 0x18, 0x6a, 0x8a,
	0x73, 0xe6, 0x33, 0x7d, 0xe1, 0xb7, 0x24, 0x96, 0xe1, 0xdd, 0x95, 0x5c, 0x67, 0xbc, 0x84, 0x24,
	0x22, 0x4a, 0x88, 0xba, 0x2b, 0x65, 0xd8, 0x7f, 0x1b, 0x30, 0x6f, 0xe6, 0xd0, 0xd5, 0x3c, 0x87,
	0xde, 0x7a, 0xed, 0x90, 0x9c, 0x91, 0xbd, 0xf5, 0x7a, 0xe9, 0x37, 0x4e, 0xad, 0xb3, 0xf3, 0xd4,
	0xba, 0x8d, 0x53, 0xdb, 0x2a, 0x2b, 0xc5, 0x59, 0xf6, 0x1a, 0x67, 0xb9, 0x80, 0xb1, 0x97, 0x60,
	0x57, 0x60, 0xdf, 0x91, 0x7a, 0xd9, 0x97, 0xa5, 0x8f, 0x34, 0x76, 0x59, 0x97, 0xcd, 0x27, 0x35,
	0x6e, 0x8e, 0xe0, 0xa5, 0xea, 0xeb, 0x02, 0x73, 0x4e, 0x18, 0xad, 0xdf, 0xcd, 0xd6, 0xe6, 0xec,
	0xbf, 0x0c, 0x78, 0xd5, 0xbe, 0xa9, 0x42, 0x09, 0xaf, 0xee, 0xe2, 0x4b, 0x5f, 0xf6, 0xcc, 0x82,
	0x00, 0xfb, 0x0e, 0xa1, 0xc5, 0x4d, 0x95, 0xc0, 0x92, 0xa2, 0xf7, 0xb0, 0xef, 0xa5, 0x49, 0x82,
	0xa9, 0x70, 0x74, 0x99, 0x8a, 0x95, 0x89, 0x46, 0xd5, 0x84, 0x29, 0x78, 0x8b, 0x09, 0x0d, 0x34,
	0x3d, 0x92, 0xb7, 0x73, 0x42, 0x03, 0xfb, 0x08, 0xa6, 0x72, 0x26, 0x5d, 0x69, 0x5a, 0xfe, 0x83,
	0x54, 0xd9, 0xdf, 0x67, 0xd7, 0xbd, 0xb6, 0x47, 0xb7, 0xb0, 0x4b, 0xdf, 0xe6, 0xd0, 0x77, 0xef,
	0x5c, 0xe1, 0x26, 0xf9, 0x3d, 0x53, 0xd6, 0xd1, 0x3f, 0x3d, 0x18, 0x1d, 0xa7, 0x62, 0x93, 0x0d,
	0x45, 0xe2, 0x61, 0x74, 0x0d, 0xcf, 0x1e, 0x0c, 0x49, 0x74, 0x70, 0xa8, 0xa7, 0xed, 0xb6, 0xe1,
	0x6a, 0x2d, 0x76, 0x44, 0xe8, 0xea, 0xce, 0x60, 0x52, 0x2b, 0x1b, 0xbd, 0xaa, 0xed, 0x69, 0x30,
	0x60, 0xbd, 0xde, 0xe2, 0xd5, 0xd9, 0x56, 0xf0, 0xb4, 0x31, 0x26, 0xd0, 0x9b, 0x7c, 0x47, 0xfb,
	0x48, 0xb5, 0xde, 0x6e, 0xf5, 0xeb, 0x9c, 0x5f, 0x43, 0x4f, 0xea, 0x3c, 0x9a, 0xe6, 0x91, 0xd5,
	0xf1, 0x61, 0xcd, 0x1a, 0x68, 0xd9, 0x57, 0x4d, 0x6f, 0xcb, 0xbe, 0xda, 0x86, 0x41, 0xd9, 0x57,
	0xbb, 0x48, 0x5f, 0xc3, 0xb3, 0x07, 0xba, 0x5a, 0xf2, 0xbf, 0x4d, 0x8f, 0x4b, 0xfe, 0xb7, 0x8b,
	0xf2, 0x8f, 0xb0, 0x5f, 0xd7, 0x26, 0x54, 0xa1, 0xb8, 0x45, 0x3d, 0xad, 0x37, 0xdb, 0xdc, 0x3a,
	0xe1, 0x4f, 0xb0, 0x5f, 0x97, 0x97, 0x32, 0x61, 0xab, 0x74, 0x95, 0x09, 0xdb, 0x55, 0xe9, 0x4b,
	0x03, 0x79, 0x30, 0x6d, 0x7b, 0xa4, 0xe8, 0x5d, 0x7d, 0x67, 0xeb, 0xbb, 0xb7, 0x3e, 0xdb, 0x1d,
	0x94, 0x7f, 0xe4, 0xa6, 0x2f, 0xff, 0x33, 0x7e, 0xf5, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb7,
	0x59, 0xe9, 0x7b, 0x4a, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthServiceClient interface {
	CheckServerStatus(ctx context.Context, in *CheckServerStatusRequest, opts ...grpc.CallOption) (*CheckServerStatusResponse, error)
	CheckUsername(ctx context.Context, in *CheckUsernameRequest, opts ...grpc.CallOption) (*CheckUsernameResponse, error)
	RegisterAccount(ctx context.Context, in *RegisterAccountRequest, opts ...grpc.CallOption) (*RegisterAccountResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	UpdateAccount(ctx context.Context, in *UpdateAccountRequest, opts ...grpc.CallOption) (*UpdateAccountResponse, error)
	GetAccountDetails(ctx context.Context, in *GetAccountDetailsRequest, opts ...grpc.CallOption) (*GetAccountDetailsResponse, error)
	ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordResponse, error)
	GetAllAccounts(ctx context.Context, in *GetAllAccountsRequest, opts ...grpc.CallOption) (AuthService_GetAllAccountsClient, error)
	GetAllSessionDetails(ctx context.Context, in *GetAllSessionDetailsRequest, opts ...grpc.CallOption) (AuthService_GetAllSessionDetailsClient, error)
}

type authServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuthServiceClient(cc *grpc.ClientConn) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) CheckServerStatus(ctx context.Context, in *CheckServerStatusRequest, opts ...grpc.CallOption) (*CheckServerStatusResponse, error) {
	out := new(CheckServerStatusResponse)
	err := c.cc.Invoke(ctx, "/authpb.AuthService/CheckServerStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) CheckUsername(ctx context.Context, in *CheckUsernameRequest, opts ...grpc.CallOption) (*CheckUsernameResponse, error) {
	out := new(CheckUsernameResponse)
	err := c.cc.Invoke(ctx, "/authpb.AuthService/CheckUsername", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) RegisterAccount(ctx context.Context, in *RegisterAccountRequest, opts ...grpc.CallOption) (*RegisterAccountResponse, error) {
	out := new(RegisterAccountResponse)
	err := c.cc.Invoke(ctx, "/authpb.AuthService/RegisterAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/authpb.AuthService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) UpdateAccount(ctx context.Context, in *UpdateAccountRequest, opts ...grpc.CallOption) (*UpdateAccountResponse, error) {
	out := new(UpdateAccountResponse)
	err := c.cc.Invoke(ctx, "/authpb.AuthService/UpdateAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetAccountDetails(ctx context.Context, in *GetAccountDetailsRequest, opts ...grpc.CallOption) (*GetAccountDetailsResponse, error) {
	out := new(GetAccountDetailsResponse)
	err := c.cc.Invoke(ctx, "/authpb.AuthService/GetAccountDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordResponse, error) {
	out := new(ChangePasswordResponse)
	err := c.cc.Invoke(ctx, "/authpb.AuthService/ChangePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetAllAccounts(ctx context.Context, in *GetAllAccountsRequest, opts ...grpc.CallOption) (AuthService_GetAllAccountsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AuthService_serviceDesc.Streams[0], "/authpb.AuthService/GetAllAccounts", opts...)
	if err != nil {
		return nil, err
	}
	x := &authServiceGetAllAccountsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AuthService_GetAllAccountsClient interface {
	Recv() (*GetAllAccountsResponse, error)
	grpc.ClientStream
}

type authServiceGetAllAccountsClient struct {
	grpc.ClientStream
}

func (x *authServiceGetAllAccountsClient) Recv() (*GetAllAccountsResponse, error) {
	m := new(GetAllAccountsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *authServiceClient) GetAllSessionDetails(ctx context.Context, in *GetAllSessionDetailsRequest, opts ...grpc.CallOption) (AuthService_GetAllSessionDetailsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AuthService_serviceDesc.Streams[1], "/authpb.AuthService/GetAllSessionDetails", opts...)
	if err != nil {
		return nil, err
	}
	x := &authServiceGetAllSessionDetailsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AuthService_GetAllSessionDetailsClient interface {
	Recv() (*GetAllSessionDetailsResponse, error)
	grpc.ClientStream
}

type authServiceGetAllSessionDetailsClient struct {
	grpc.ClientStream
}

func (x *authServiceGetAllSessionDetailsClient) Recv() (*GetAllSessionDetailsResponse, error) {
	m := new(GetAllSessionDetailsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AuthServiceServer is the server API for AuthService service.
type AuthServiceServer interface {
	CheckServerStatus(context.Context, *CheckServerStatusRequest) (*CheckServerStatusResponse, error)
	CheckUsername(context.Context, *CheckUsernameRequest) (*CheckUsernameResponse, error)
	RegisterAccount(context.Context, *RegisterAccountRequest) (*RegisterAccountResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	UpdateAccount(context.Context, *UpdateAccountRequest) (*UpdateAccountResponse, error)
	GetAccountDetails(context.Context, *GetAccountDetailsRequest) (*GetAccountDetailsResponse, error)
	ChangePassword(context.Context, *ChangePasswordRequest) (*ChangePasswordResponse, error)
	GetAllAccounts(*GetAllAccountsRequest, AuthService_GetAllAccountsServer) error
	GetAllSessionDetails(*GetAllSessionDetailsRequest, AuthService_GetAllSessionDetailsServer) error
}

// UnimplementedAuthServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (*UnimplementedAuthServiceServer) CheckServerStatus(ctx context.Context, req *CheckServerStatusRequest) (*CheckServerStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckServerStatus not implemented")
}
func (*UnimplementedAuthServiceServer) CheckUsername(ctx context.Context, req *CheckUsernameRequest) (*CheckUsernameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckUsername not implemented")
}
func (*UnimplementedAuthServiceServer) RegisterAccount(ctx context.Context, req *RegisterAccountRequest) (*RegisterAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterAccount not implemented")
}
func (*UnimplementedAuthServiceServer) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedAuthServiceServer) UpdateAccount(ctx context.Context, req *UpdateAccountRequest) (*UpdateAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAccount not implemented")
}
func (*UnimplementedAuthServiceServer) GetAccountDetails(ctx context.Context, req *GetAccountDetailsRequest) (*GetAccountDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccountDetails not implemented")
}
func (*UnimplementedAuthServiceServer) ChangePassword(ctx context.Context, req *ChangePasswordRequest) (*ChangePasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangePassword not implemented")
}
func (*UnimplementedAuthServiceServer) GetAllAccounts(req *GetAllAccountsRequest, srv AuthService_GetAllAccountsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAllAccounts not implemented")
}
func (*UnimplementedAuthServiceServer) GetAllSessionDetails(req *GetAllSessionDetailsRequest, srv AuthService_GetAllSessionDetailsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAllSessionDetails not implemented")
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_CheckServerStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckServerStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).CheckServerStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authpb.AuthService/CheckServerStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).CheckServerStatus(ctx, req.(*CheckServerStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_CheckUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckUsernameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).CheckUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authpb.AuthService/CheckUsername",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).CheckUsername(ctx, req.(*CheckUsernameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_RegisterAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).RegisterAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authpb.AuthService/RegisterAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).RegisterAccount(ctx, req.(*RegisterAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authpb.AuthService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_UpdateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).UpdateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authpb.AuthService/UpdateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).UpdateAccount(ctx, req.(*UpdateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetAccountDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetAccountDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authpb.AuthService/GetAccountDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetAccountDetails(ctx, req.(*GetAccountDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authpb.AuthService/ChangePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ChangePassword(ctx, req.(*ChangePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetAllAccounts_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetAllAccountsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AuthServiceServer).GetAllAccounts(m, &authServiceGetAllAccountsServer{stream})
}

type AuthService_GetAllAccountsServer interface {
	Send(*GetAllAccountsResponse) error
	grpc.ServerStream
}

type authServiceGetAllAccountsServer struct {
	grpc.ServerStream
}

func (x *authServiceGetAllAccountsServer) Send(m *GetAllAccountsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _AuthService_GetAllSessionDetails_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetAllSessionDetailsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AuthServiceServer).GetAllSessionDetails(m, &authServiceGetAllSessionDetailsServer{stream})
}

type AuthService_GetAllSessionDetailsServer interface {
	Send(*GetAllSessionDetailsResponse) error
	grpc.ServerStream
}

type authServiceGetAllSessionDetailsServer struct {
	grpc.ServerStream
}

func (x *authServiceGetAllSessionDetailsServer) Send(m *GetAllSessionDetailsResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "authpb.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckServerStatus",
			Handler:    _AuthService_CheckServerStatus_Handler,
		},
		{
			MethodName: "CheckUsername",
			Handler:    _AuthService_CheckUsername_Handler,
		},
		{
			MethodName: "RegisterAccount",
			Handler:    _AuthService_RegisterAccount_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _AuthService_Login_Handler,
		},
		{
			MethodName: "UpdateAccount",
			Handler:    _AuthService_UpdateAccount_Handler,
		},
		{
			MethodName: "GetAccountDetails",
			Handler:    _AuthService_GetAccountDetails_Handler,
		},
		{
			MethodName: "ChangePassword",
			Handler:    _AuthService_ChangePassword_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAllAccounts",
			Handler:       _AuthService_GetAllAccounts_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetAllSessionDetails",
			Handler:       _AuthService_GetAllSessionDetails_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "authpb/authpb.proto",
}
